[workspace]

members = [
    "hashmap",
    "string",
    "modules_",
    "crates_",
    "mutable_reference",
    "lifetimes",
    "structs",
    "iterators",
    "weak_references",

    "traits/impl-fromstr",    
]